name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Ensure package is publishable
        id: check
        run: |
          node -e "const pkg=require('./package.json'); if(pkg.private){ console.log('package.json.private=true — skipping publish'); process.exit(78); }"
      - name: Publish package
        if: steps.check.outcome == 'success'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Publishing to npm..."
          npm publish --access public
